### ISSUE TITLE
TUI on windows

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#208]
In GitLab by @maerwald on Jul 30, 2021, 03:26

brick doesn't work on windows. What are our options?

**Comment by thma** [comment]
> however... `ansi-terminal-game` doesn't seem to have a notion of viewport like brick. So scrolling and drawing only what fits into the terminal isn't supported. That feels like that would need a lot of work.

I'd be very happy to see a GhcUp TUI on windows, so I came across this issue discussion.
As it seams that using `ansi-terminal-game` involves a lot of additional work I tried to find out why bricks has no windows support. It turns out that bricks relies on the `vty` library which does not provide windows support as of now.

But is seems that they already started to work on this: 
https://github.com/jtdaugherty/vty/milestone/1

So IMO it would be better to fix the issue upstream - that is in `vty` - as this would provide windows support for all apps relying on `bricks` and `vty`.

**Comment by hasufell** [comment]
@thma doesn't look like anyone is working on that at the moment

**Comment by jtdaugherty** [comment]
Hi all, I wanted to drop by and let you know that Brick's support for Windows is on the way by way of support for Windows in its underlying library, Vty. I've mentioned that here in the past but over the last few months there has been a lot of promising activity toward a Windows release of Vty, with an update to Brick to follow.

If you are interested, you can see the status of the work here:

https://github.com/jtdaugherty/vty/issues/260

**Comment by hasufell** [comment]
There's been some issues building GHCup/brick on recent GHCs and I think vty raised the minimum required version. That might need some investigation.

@Ismor has been doing work to modernize the brick related code: https://github.com/haskell/ghcup-hs/pull/850

Maybe he can champion it? I'm very sick at the moment.

**Comment by ulysses4ever** [comment]
> I'm very sick at the moment.

I'm very sorry about that! Please, get well!

**Comment by lsmor** [comment]
> Maybe he can champion it?

Let me try! ;) 

btw, I think you quoted the wrong user haha

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-hs/pull/912
