### ISSUE TITLE
"Failed to parse cabal symlink target" warning

### ISSUE THREAD

**Issue by TerrorJack** [haskell/ghcup-hs#741]
I've seen the similar warning when using ghcup to install ghc in a container:

```
[ Warn  ] Failed to parse cabal symlink target with: /workspace/.local/bin/cabal: getSymbolicLinkTarget:readSymbolicLink: invalid argument (Invalid argument). The symlink /workspace/.local/bin/cabal needs to point to valid cabal binary, such as 'cabal-3.4.0.0'.
```

The problem here is: `ghcup` is installed with `BOOTSTRAP_HASKELL_MINIMAL=1`, and I've never called `ghcup install cabal`. The `cabal` executable is a manually installed prerelease. So even when `cabal` is not installed by `ghcup`, it still attempts to parse it as a symlink and produces this incorrect warning.

**Comment by hasufell** [comment]
You're using XDG support?

**Comment by hasufell** [comment]
> it still attempts to parse it as a symlink and produces this incorrect warning.

Why would that be an incorrect warning? GHCup doesn't use an internal database to figure out what is installed and what isn't. It does so by inspecting certain internal directories as well as inspecting binaries in `bin/` dir.

It warns you because installing cabal via ghcup now would likely lead to unexpected results.

We can't anticipate whether you want to install cabal or not.

Inspecting these files is necessary.

The alternative is moving all installations into subdirs, e.g. `~/.ghcup/cabal/<ver>/cabal` and then only using bindir for symlinking and being more permissive. See https://github.com/haskell/ghcup-hs/issues/375

But this would be a breaking change and would require migration code or so. All of this is hard, because we don't want the end user to ever know about any of this.

**Comment by TerrorJack** [comment]
> You're using XDG support?

Yes, though I believe the warning is the same if I manually install `cabal` executable to `~/.local/bin` without using XDG support.

> Inspecting these files is necessary.

Sure! Just saying that maybe it's worthwhile to add logic to check if `cabal` is a symlink and bail out of rest of version checking logic if it's not a symlink, since that suggests `cabal` is user-installed and out of `ghcup`'s control.

**Comment by hasufell** [comment]
> Yes, though I believe the warning is the same if I manually install cabal executable to ~/.local/bin without using XDG support.

No.

**Comment by hasufell** [comment]
> Sure! Just saying that maybe it's worthwhile to add logic to check if cabal is a symlink and bail out of rest of version checking logic if it's not a symlink, since that suggests cabal is user-installed and out of ghcup's control.

I don't understand what you mean.

GHCup already gracefully handles this case... and in addition prints the warning. 

You don't want to see the warning, but there's no good heuristic when it's a good idea to show it. You're already in a corner use case.

The only solution I see is the one I described above.

**Comment by TerrorJack** [comment]
> No.

Ah, good to know that :)

> You're already in a corner use case.

Sure, that's fair enough; I had a wrong impression that for `cabal` installations outside of `ghcup`'s management, `ghcup` could recognize that `cabal` is not its business (by checking `cabal` is not a symlink), and not produce the warning message. But it's not true and the warning is not a big annoyance either.

Thanks for taking your time and good to know something more about ghcup internals :)
