### ISSUE TITLE
curl: (6) Could not resolve host: get-ghcup.haskell.org

### ISSUE THREAD

**Issue by BrianHare** [haskell/ghcup-hs#820]
My comment from earlier this morning about things installing was premature. 

Installed WSL 2 on Windows 10, Ubuntu.  Ran 

curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

copied from https://www.haskell.org/ghcup/install/.  Got the above error message. 

Likely temporary/transient issue, try again later? Or something else going on? Suggestions appreciated.

**Comment by hasufell** [comment]
Sounds like a configuration issue. There seem to be some suggestions here https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6

Why are you using WSL2 now? Did the powershell installation not work?

**Comment by BrianHare** [comment]
Sorry, I'm leaving out a bit of context.

The first attempt (failed curl etc) was on powershell, and no, it didn't work. I tried following the steps for a manual install, but again, issues around curl. But after some poking around, I found Stack, and got it running; I can get to GHCi and compile "Hello world," so that seems to be doing OK.  That's on my home machine-several years old, running consumer-model Windows 10.

Then the attempt to get things installed on my work laptop, a relatively new Dell running Win10 Enterprise. Some of the security settings are managed by the organization, and thereby hangs a tale. The standard windows install script failed immediately over the attempt to reset the exceptions policy.  I got Stack running, after some tweaking, though I have to run it as administrator (though I think I've figured out a workaround for that). A student had mentioned how smooth the WSL installation went for them, so giving that a try. If it's a configuration issue or I'm bumping up against the university computer security policies (distinctly possible), OK, I'll try to find a workaround.

The issue is that I'm revising a functional programming course and considering switching to Haskell as the implementation language. Students will want to install it on their own machines, and a lot of them will be on Windows. I want to be reasonably confident there's a smooth installation process they can follow.

As for the issue in question with resolving the host, when I go to that URL in Firefox on Windows, I get back a text file with the installation script, so it does seem to be an issue with WSL. Thank you for the link. I'm off to a conference, so it'll probably be sometime Sunday before I can look at it in detail. I'll keep you posted, and I apologize if I provided more background than you ever wanted to know....  (never ask a professor to explain something unless you want ALL the explanation....)

Thanks again,

Brian K. Hare (he/him)
Teaching Professor
Division of Computing, Analytics, and Mathematics
School of Science & Engineering
450 E Flarsheim Hall
Phone: 816-235-2362<tel:816-235-2362>
[UMKC School of Science and Engineering Logo]<https://sse.umkc.edu/>
"Shun wishful thinking, ignore divine revelation, forget what 'the stars foretell,' avoid opinion, care not what the neighbors think, never mind the unguessable 'verdict of history' - what are the facts, and to how many decimal places?"                      --R. A. Heinlein

**Comment by hasufell** [comment]
> I tried following the steps for a manual install, but again, issues around curl.

Can you be more specific here? The manual installation doesn't need curl.

> The issue is that I'm revising a functional programming course and considering switching to Haskell as the implementation language

My mission is to improve installation experience in Haskell. So I'll try to support you as much as I can.

There are already a couple of universities using ghcup and the only issues that pop up now and then are on windows.

These are mostly due to:

- old windows or old powershell (win 7 doesn't work properly)
- no proper `curl.exe` that causes issues with the script (can be disabled as I showed)
- aggressive windows defender or antivirus configuration
- issues with network or other administrative policies (this is a hard one, I'd need more details to reproduce and find solutions)

When it's about WSL2 (make sure you're using WSL2, not WSL1), the most common issue is with DNS resolution or other networking stuff. This isn't a ghcup issue per se and will affect other tools as well.

The fact that stack somewhat works is, because it uses its own Haskell TLS implementation and doesn't depend on curl/wget or other tools. I chose to not do that, because that TLS implementation is not audited.

----

I think we should focus on getting the manual installation process working for now. I'm fairly confident it should work, even in a quite restrictive setting... the only prerequisites are:

1. you can download binaries from the internet and your university proxy/gateway will not block it
2. you can execute binaries that install stuff (especially msys2) or you have an msys2 pre-installed (do you?)
