### ISSUE TITLE
Cannot add multiple prerelease channels?

### ISSUE THREAD

**Issue by phadej** [haskell/ghcup-hs#922]
It looks like 

```
% ~/.ghcup/bin/ghcup config add-prerelease-channel https://raw.githubusercontent.com/haskell/ghcup-metadata/develop/ghcup-cross-0.0.8.yaml
```

does nothing if I already have (another) prerelease channel. My config looks like

```
...
url-source:
- GHCupURL
- https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml
verbose: false
```

before and after the command.

That is very unconvenient, if one cannot add multiple prerelease channels, nor there are command to remove any.

---

Maybe `add-prerelease-channel` doesn't work at all?

**Comment by phadej** [comment]
It's `add-release-channel`. `ghcup` just silently does nothing on a wrong command. That is a bug.

**Comment by hasufell** [comment]
Not really a bug, just confusing behavior.

What happens here that `ghcup config <key> <value>` is a shorthand for `ghcup config set <key> <value>`. Additionally, ghcup is a bit too lax when the `key` (`add-prerelease-channel` here) doesn't exist... decoding does not fail.

I fixed both here: https://github.com/haskell/ghcup-hs/pull/926

* `ghcup config <key> <value>` is no longer valid
* `ghcup config set <non-existent-key> <value>` will now properly error instead of doing nothing
