### ISSUE TITLE
cabal.ghc8107.project doesn't work (update cabal.ghc8107.project.freeze?)

### ISSUE THREAD

**Issue by runeksvendsen** [haskell/ghcup-hs#948]
I'm trying to build the ghcup executable using GHC 8.10.7 via the `cabal.ghc8107.project` project config. I get the error below.  
It looks like the .cabal file specifies `vty ^>= 6.0` while `cabal.ghc8107.project.freeze` specifies `vty == 5.37`.

```
$ cabal --project-file=cabal.ghc8107.project build exe:ghcup
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: ghcup-0.1.20.0 (user goal)
[__1] trying: ghcup:-no-exe
[__2] rejecting: ghcup:-tui (constraint from config file, command line flag,
or user target requires opposite flag selection)
[__2] trying: ghcup:+tui
[__3] next goal: vty (dependency of ghcup -no-exe +tui)
[__3] rejecting: vty-5.37 (conflict: ghcup +tui => vty^>=6.0)
[__3] rejecting: vty-5.36, vty-5.35.1, vty-5.35, vty-5.34, vty-5.33, vty-5.32,
vty-5.31, vty-5.30, vty-5.29, vty-5.28.2, vty-5.28.1, vty-5.28, vty-5.27,
vty-5.26, vty-5.25.1, vty-5.25, vty-5.24.1, vty-5.24, vty-5.23.1, vty-5.23,
vty-5.22, vty-5.21, vty-5.20, vty-5.19.2, vty-5.19.1, vty-5.19, vty-5.18.1,
vty-5.18, vty-5.17.1, vty-5.17, vty-5.16, vty-5.15.1, vty-5.15, vty-5.14,
vty-5.13, vty-5.11.3, vty-5.11.2, vty-5.11.1, vty-5.11, vty-5.10, vty-5.9.1,
vty-5.9, vty-5.8.1, vty-5.8, vty-5.7.1, vty-5.7, vty-5.6, vty-5.5.0,
vty-5.4.0, vty-5.3.1, vty-5.3, vty-5.2.11, vty-5.2.10, vty-5.2.9, vty-5.2.8,
vty-5.2.7, vty-5.2.6, vty-5.2.5, vty-5.2.4, vty-5.2.3, vty-5.2.2, vty-5.2.1,
vty-5.2.0, vty-5.1.4, vty-5.1.3, vty-5.1.1, vty-5.1.0, vty-5.0.2, vty-5.0.1,
vty-5.0.0, vty-4.7.5, vty-4.7.4, vty-4.7.3, vty-4.7.2, vty-4.7.1,
vty-4.7.0.20, vty-4.7.0.18, vty-4.7.0.14, vty-4.7.0.12, vty-4.7.0.10,
vty-4.7.0.8, vty-4.7.0.6, vty-4.7.0.4, vty-4.7.0.0, vty-4.6.0.6, vty-4.6.0.4,
vty-4.6.0.2, vty-4.6.0.1, vty-4.4.0.0.1, vty-4.4.0.0, vty-4.2.1.0,
vty-4.0.0.1, vty-4.0.0, vty-3.1.8.4, vty-3.1.8.2, vty-3.1.8, vty-3.1.6,
vty-3.1.4, vty-3.1.2, vty-3.1.0, vty-3.0.4, vty-3.0.2, vty-3.0.1, vty-3.0.0,
vty-5.12 (constraint from project config
/Users/rune/code/ghcup-hs/cabal.ghc8107.project.freeze requires ==5.37)
[__3] fail (backjumping, conflict set: ghcup, vty, ghcup:no-exe, ghcup:tui)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: vty, ghcup, ghcup:tui, ghcup:no-exe
Try running with --minimize-conflict-set to improve the error message.
```

**Comment by runeksvendsen** [comment]
Deleting the .freeze file makes planning succeed

**Comment by hasufell** [comment]
There's a script to update the freeze files:

- https://github.com/haskell/ghcup-hs/blob/master/scripts/dev/refreeze.sh

Unfortunately we don't really test them in CI. So that's probably why they're always broken. 

One of the main issues with building is symbol clashes with libarchive:

- https://github.com/vmchale/libarchive/issues/33

The solution there is to use a proper autoconf build setup.

**Comment by hasufell** [comment]
I've also been trying to update the tool versions in ci: https://github.com/haskell/ghcup-hs/pull/946

**Comment by hasufell** [comment]
The newer cabal versions allow to specify ghc version [conditionals](https://cabal.readthedocs.io/en/stable/cabal-project.html#conditionals-and-imports) in `cabal.project` and `cabal.project.freeze` so we could utilize those. But that would mean you can't build ghcup with the 'recommended' cabal, which is 3.6.2.0 still.

Extracting the versions from `tested-with` is possible, but `==` cause quite some churn. GHCup allows to use `ghc-8.10` etc without the minor version, so that would be preferable.

----

Wrt libarchive... there's no way at the moment. That would require patching libarchive, to allow a proper configure phase for its bundled C sources.

**Comment by hasufell** [comment]
https://github.com/vmchale/libarchive/pull/35

**Comment by runeksvendsen** [comment]
For now I have updated cabal.ghc8107.project(.freeze) files to at least fix that. PR: https://github.com/haskell/ghcup-hs/pull/961. It's currently marked as draft, and I will mark it as ready when the builds finish on both my macOS and Linux machines.

Side note: running the update script fails on Ubuntu 22.04.3:

```
$ ./scripts/dev/refreeze.sh '8.10.7'
+ rm -f cabal.ghc8107.project
+ rm -f cabal.ghc8107.project.freeze
./scripts/dev/refreeze.sh: 10: Bad substitution
```

It works when I run it with bash 5.2.15.

More info:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

$ head -1 ./scripts/dev/refreeze.sh
#!/bin/sh

$ readlink -f /bin/sh
/usr/bin/dash

$ apt-cache policy dash
dash:
  Installed: 0.5.11+git20210903+057cd650a4ed-3build1
  Candidate: 0.5.11+git20210903+057cd650a4ed-3build1
  Version table:
 *** 0.5.11+git20210903+057cd650a4ed-3build1 500
        500 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 Packages
        100 /var/lib/dpkg/status
```

**Comment by hasufell** [comment]
Was fixed
