### ISSUE TITLE
`git describe` is not generally reliable as a way of getting version information

### ISSUE THREAD

**Issue by michaelpj** [haskell/ghcup-hs#998]
Reported by a user when running `ghcup compile hls -g master --git-describe-version`, they get
```
[ Info  ] Examining git ref master
[ ...   ]   HLS version (from cabal file): 2.6.0.0
[ ...   ]   'git describe' output: 2.2.0.0-206-g902a62bb
[ ...   ]   commit hash: 902a62bb6be0f1f7cfb5e139078505696b514203
[ Info  ] Building HLS 2.2.0.0-206-g902a62bb for GHC version 9.2.8
```

The issue here is that HLS's release process goes like this:
- Make a release branch
- Release binaries from the tip of the release branch and tag
- Squash-merge the release branch into master (we squash-merge all PRs)

The net effect of this is that while the release-tagged commit is "morally" an ancestor of `master`, it is not technically an ancestor of `master`, and so `git describe` doesn't find it.

Leaving aside whether this is a sensible process (I believe that other projects do similar things, it's not a crazy outlier), probably we can't assume that release tags _are_ ancestors of `master`, and so using `git describe` isn't a good idea in general.

**Comment by hasufell** [comment]
I'm not sure what I am expected to do here. I don't think that introducing complex logic to deal with repository branching schemes is something that I'm willing to do.

`--git-describe-version` has simple semantics. If you don't want it, then **just omit it**. GHCup will then parse the `.cabal` file and derive HLS version from that.

https://github.com/haskell/ghcup-hs/blob/2a79c669a5057f99f7a7718a93a566e65520b7d7/lib/GHCup/HLS.hs#L462

If that conflicts with a current installation, then use `--overwrite-version` to set something else.

**Comment by michaelpj** [comment]
I'm definitely not suggesting we have weird conditional logic. I guess it does seem like `--git-describe-version` is a bit of a footgun, in that it doesn't always work and it's not clear why (it took a few of us in the channel quite a while to figure out). So maybe it's not a good feature?

The combination of using the version from the cabal file plus the git hash seems good, I don't know if that's an option.

cc @konn who reported this, maybe they have more of a sense of what they would like to happen.

**Comment by konn** [comment]
Hi, thank you @michaelpj for opening this issue!

Given that `git describe`-based version generation seems unsuitable with the current HLS release, perhaps abolishing the feature would be good. Or, if GHCup already parses `.cabal` to get version, it would be good if there is an option to set version name to something like:

```
2.6.0.0-b91c907
```

or, slightly verbosely,

```
2.6.0.0-master-b91c907
```

The point is, in this way we can distinguish between proper release version and those compiled from specific branch/commits and which seems similar to the past behaviour of ``--git-describe-version`. One virtue of this is that the user don't have to find out commit hash beforehand.

**Comment by hasufell** [comment]
> perhaps abolishing the feature would be good

It is also used for GHC.

I'm hesitant to selectively remove features, just because upstream has a particular branching model. `git describe` is just a way to disambiguate versions in a total way. We could as well just use the full commit hash, but it's less descriptive. 

> if there is an option to set version name to something like

What would the switch even be named? I think this won't be any easier to grok for casual users. I try to keep `--help` clean of advanced features.

GHCup already has many flags that are not documented, because they're advanced usage. I'm fine adding something like this to that advanced set and hiding it from the help output. But I'm reluctant to expose it to everyone.

**Comment by runeksvendsen** [comment]
I think it could make sense for the default version tag produced by GHCup's `compile` command to be different from that of the `install` command.

Perhaps something like @konn suggests, ie: `<version_parsed_from_cabal_file>-<branch_name>-<short_commit_hash>` (e.g. `2.6.0.0-master-b91c907`).

**Comment by runeksvendsen** [comment]
> > I think it could make sense for the default version tag produced by GHCup's compile command to be different from that of the install command.
> 
> I don't think I agree. It makes it harder to predict behavior.
> 
> If you install version 2.2.0.0, you'd expect it to be named 2.2.0.0.

The use case I'm thinking of is managing bleeding edge HLS versions using GHCup, e.g. compiled from HLS `master`, where the Cabal version is too granular.

When running `ghcup compile hls -g master` twice, between which the tip of the HLS `master` branch changes, the latter run overwrites the former version (because the Cabal version identifier is the same). With the proposed version identifier (ie. including the commit hash), GHCup is able to manage both versions simultaneously, because it recognizes that they're different even though they have the same Cabal version.

**Comment by hasufell** [comment]
> > > I think it could make sense for the default version tag produced by GHCup's compile command to be different from that of the install command.
> > 
> > 
> > I don't think I agree. It makes it harder to predict behavior.
> > If you install version 2.2.0.0, you'd expect it to be named 2.2.0.0.
> 
> The use case I'm thinking of is managing bleeding edge HLS versions using GHCup, e.g. compiled from HLS `master`, where the Cabal version is too granular.
> 
> When running `ghcup compile hls -g master` twice, between which the tip of the HLS `master` branch changes, the latter run overwrites the former version (because the Cabal version identifier is the same). With the proposed version identifier (ie. including the commit hash), GHCup is able to manage both versions simultaneously, because it recognizes that they're different even though they have the same Cabal version.

Yes, as I said: you'll be introducing *heuristics* based on **branch names**. Is that the behavior you want for `ghcup compile hls -g 2.6.0.0` or for `ghcup compile -v 2.6.0.0`? We don't know.

Does the user want a new separate bindist every time they run `ghcup compile hls -g master`? We also don't know.

And finally: there's some caveats about versions in GHCup that are not strictly PVP. GHCup can handle it, but some features may not work, because it can't make sense out of the version. So doing non-PVP versions by default does not seem appealing.

**Comment by hasufell** [comment]
I'm inclined to add something like a pattern:

```
git compile hls -g master --version-pattern="%v-foo-%h
```

Where we have:

```
%v    version from cabal file
%b    branch/tag name
%h    short commit hash
%H    long commit hash
%g    'git describe' output
```

**Comment by konn** [comment]
> I'm inclined to add something like a pattern:
> 
> ```
> git compile hls -g master --overwrite-version="%v-foo-%h
> ```

Ah, I like this! This would give us more flexibility on versioning and has less program-specific assumptions!

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-hs/pull/1005
